[package]
name = "serialtui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30"
serialport = "4.6"
anyhow = "1"
chrono = "0.4"

[profile.release]
strip = true
lto = true
codegen-units = 1
